import type { Metadata } from 'next';

import './globals.css';
import Head from 'next/head';
import { AuthProvider } from '@/lib/AuthContext';
import { ThemeProvider } from '@/lib/ThemeContext';

const robotoMono = {
  fontFamily: "'Roboto Mono', monospace",
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head>
        <link
          href='https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@100;400;700&display=swap'
          rel='stylesheet'
        />
      </Head>
      <body style={{ fontFamily: robotoMono.fontFamily }}>
        <ThemeProvider>
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
